# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-08 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20180208_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tag',
            field=models.CharField(default='', max_length=20, verbose_name='课程标签'),
        ),
    ]
